export const ANIMATION_CLIPS = [
  'Idle',
  'Walk',
  'Carry',
  'Gesture',
  'Sit',
  'Row',
  'Haul',
  'Kneel',
  'Recline',
  'Rise',
  'MatCarry',
  'Use',
] as const;
export type ActorClip = (typeof ANIMATION_CLIPS)[number];
export const ACTOR_ASSETS = [
  'traveler',
  'simon',
  'miriam',
  'jesus',
  'villager',
  'james',
  'john',
  'hannah',
  'amos',
  'ruth',
  'bearer',
  'healed_man',
] as const;
export type ActorAsset = (typeof ACTOR_ASSETS)[number];
export const PROP_ASSETS = [
  'house',
  'house_large',
  'market',
  'olive',
  'cypress',
  'palm',
  'boat',
  'nets',
  'crate',
  'amphora',
  'reeds',
  'rock',
  'well',
  'basket_empty',
  'basket_fish',
  'net_folded',
  'net_cast',
  'net_full',
  'oar',
  'bread_bundle',
  'mooring',
  'landing_mat',
  'room_wall',
  'low_wall',
  'doorway',
  'roof_opening',
  'roof_panel',
  'gate',
  'exterior_steps',
  'oven',
  'worktable',
  'bench',
  'stool',
  'shelf',
  'jug',
  'bread_basket',
  'handcart',
  'cart_handle',
  'mat_flat',
  'mat_rolled',
  'flour_sack',
] as const;
export type AssetId = ActorAsset | (typeof PROP_ASSETS)[number];
export interface AssetDefinition {
  id: AssetId;
  kind: 'actor' | 'prop';
  maxTriangles: number;
  clips: readonly ActorClip[];
  attachments: readonly string[];
}
export const assets: readonly AssetDefinition[] = [
  ...ACTOR_ASSETS.map((id) => ({
    id,
    kind: 'actor' as const,
    maxTriangles: 5000,
    clips: ANIMATION_CLIPS,
    attachments: ['carry_socket'],
  })),
  ...PROP_ASSETS.map((id) => ({
    id,
    kind: 'prop' as const,
    maxTriangles: 10000,
    clips: [],
    attachments:
      id === 'boat'
        ? ['seat_front', 'seat_middle', 'seat_back', 'net_socket', 'oar_left', 'oar_right']
        : [],
  })),
];
export const VILLAGE_ASSETS: readonly AssetId[] = [
  'traveler',
  'simon',
  'miriam',
  'jesus',
  'villager',
  'james',
  'john',
  'house',
  'house_large',
  'market',
  'olive',
  'cypress',
  'palm',
  'boat',
  'nets',
  'crate',
  'amphora',
  'reeds',
  'rock',
  'well',
  'basket_empty',
  'basket_fish',
  'net_folded',
  'oar',
  'bread_bundle',
  'mooring',
  'landing_mat',
];
export const NEIGHBORHOOD_ASSETS: readonly AssetId[] = [
  'traveler',
  'hannah',
  'amos',
  'ruth',
  'villager',
  'house',
  'house_large',
  'olive',
  'well',
  'amphora',
  'crate',
  'room_wall',
  'low_wall',
  'doorway',
  'roof_opening',
  'roof_panel',
  'gate',
  'exterior_steps',
  'oven',
  'worktable',
  'bench',
  'stool',
  'shelf',
  'jug',
  'bread_basket',
  'handcart',
  'cart_handle',
  'mat_flat',
  'mat_rolled',
  'flour_sack',
];
export const ROOF_ASSETS: readonly AssetId[] = [
  'jesus',
  'bearer',
  'healed_man',
  'villager',
  'room_wall',
  'doorway',
  'low_wall',
  'roof_opening',
  'mat_flat',
  'mat_rolled',
  'bench',
];
export const LAKE_ASSETS: readonly AssetId[] = [
  'boat',
  'oar',
  'net_folded',
  'net_cast',
  'net_full',
  'basket_fish',
  'simon',
  'jesus',
  'james',
  'john',
  'villager',
  'miriam',
  'reeds',
  'rock',
  'palm',
  'house',
];
export function isActorAsset(id: string): id is ActorAsset {
  return ACTOR_ASSETS.some((candidate) => candidate === id);
}
